# Generated by Django 2.1.2 on 2018-10-20 11:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('request_path', models.TextField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
                ('body_bytes_sent', models.IntegerField(blank=True, default=None, null=True)),
                ('http_referer', models.TextField(blank=True, default=None, null=True)),
                ('http_user_agent', models.TextField(blank=True, default=None, null=True)),
                ('forwarded_for', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(blank=True, default=None, null=True), blank=True, default=list, size=None)),
            ],
            options={
                'get_latest_by': 'create_time',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=8, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=8, null=True)),
                ('timezone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('isp', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('org', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('_as', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accesslog',
            name='client_addr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_addr_log', to='underworld.IP'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='remote_addr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remote_addr_log', to='underworld.IP'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['create_time'], name='underworld__create__3747b3_idx'),
        ),
    ]
